---
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
  - name: Pause for 1 minutes to build an app cache
    pause:
      minutes: 1

  - name: Install prerequisites
    apt:
      name:
        - apt-transport-https
        - libcurl3-gnutls
        - ca-certificates
      state: present
      update_cache: yes

  - name: Add an APT key
    apt_key:
      id: EA312927
      keyserver: keyserver.ubuntu.com

  - name: Add an APT repository
    apt_repository:
      repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
      state: present

  - name: Install a mongodb package
    apt:
      name: mongodb-org
      state: present
      allow_unauthenticated: yes
      update_cache: yes

  - name: Configure the mongo service
    systemd:
      name: mongod
      enabled: yes
